#For Docker and Prod server
server:
  port: 8181
management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
  output:
    ansi:
      enabled: DETECT

telegram:
  bot:
    token: ${INST_TELEGRAM_BOT_TOKEN}
    name: ${INST_TELEGRAM_BOT_NAME}
    reconnectTimeout: 10000
    adminId: ${INST_TELEGRAM_ADMIN_ID}

logging:
  level:
    root: INFO
    com.dp_ua: INFO

  file:
    name: ./logs/file.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
